spring:
  datasource:
    url: ${LMS_DATASOURCE_URL}
    username: ${LMS_DATASOURCE_USERNAME}
    password: ${LMS_DATASOURCE_PASSWORD}
    driver-class-name: ${LMS_DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}
  jpa:
    hibernate:
      ddl-auto: update
