server:
  port: 8090

spring:
  application:
    name: library-management-system
  datasource:
    url: ${LMS_DATASOURCE_URL}
    username: ${LMS_DATASOURCE_USERNAME}
    password: ${LMS_DATASOURCE_PASSWORD}
    driver-class-name: ${LMS_DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false

app:
  security:
    remember-me-key: ${LMS_REMEMBER_ME_KEY}
